Capture.create(event: 'create a product', data: {email: 'giraffe@zoo.com', tennant: 'Das box store', product_name: 'medium box', customized: 'false', clicked: 'top button'})
Capture.create(event: 'create a product', data: {email: 'zebra@zoo.com', tennant: 'Das box store', product_name: 'small box', customized: 'true', clicked: 'top button'})
Capture.create(event: 'create a product', data: {email: 'giraffe@zoo.com', tennant: 'Das box store', product_name: 'big box', customized: 'false', clicked: ' bottom button'})
Capture.create(event: 'create a product', data: {email: 'otter@zoo.com', tennant: 'Das box store', product_name: 'mini box', customized: 'true', clicked: 'top button'})
Capture.create(event: 'create a product', data: {email: 'otter@zoo.com', tennant: 'Das box store', product_name: 'minish box', customized: 'true', clicked: 'top button'})
Capture.create(event: 'create a product', data: {email: 'otter@zoo.com', tennant: 'Das box store', product_name: 'folding box', customized: 'false', clicked: 'bottom button'})

Capture.create(event: 'create a user', data: {email: 'otter@zoo.com', tennant: 'Das box store', invitation: 'true', walk_in: 'false'})
Capture.create(event: 'create a user', data: {email: 'otter@zoo.com', tennant: 'Das box store', invitation: 'true', walk_in: 'false'})
Capture.create(event: 'create a user', data: {email: 'otter@zoo.com', tennant: 'Das box store', invitation: 'true', walk_in: 'false'})
Capture.create(event: 'create a user', data: {email: 'zebra@zoo.com', tennant: 'Das box store', invitation: 'false', walk_in: 'true'})


Capture.create(event: 'login', data: {email: 'jaguar@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'jaguar@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'jaguar@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'jaguar@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'zebra@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'zebra@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'zebra@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'zebra@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'zebra@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'giraffe@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'giraffe@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'giraffe@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'giraffe@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'otter@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'otter@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'otter@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'otter@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'otter@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'otter@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'otter@zoo.com', tennant: 'Das box store'})
Capture.create(event: 'login', data: {email: 'otter@zoo.com', tennant: 'Das box store'})
